# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xci
# IP: The module: 'top_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ps7_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xci
# IP: The module: 'top_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ps7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
