# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top}]

# IP: bd/top/ip/top_ps7_0/top_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_ps7_0 || ORIG_REF_NAME==top_ps7_0}]

# IP: bd/top/ip/top_dht11_sa_top_0/top_dht11_sa_top_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_dht11_sa_top_0 || ORIG_REF_NAME==top_dht11_sa_top_0}]

# XDC: bd/top/top_ooc.xdc
