# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /homes/palmiero/Desktop/DHT11_Controller/top.cache/wt [current_project]
set_property parent.project_path /homes/palmiero/Desktop/DHT11_Controller/top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /homes/palmiero/Desktop/DHT11_Controller/dht11_sa_top [current_project]
set_property ip_output_repo /homes/palmiero/Desktop/DHT11_Controller/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/hdl/top_wrapper.v
add_files /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xdc]
set_property used_in_implementation false [get_files -all /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/top_ooc.xdc]
set_property is_locked true [get_files /homes/palmiero/Desktop/DHT11_Controller/top.srcs/sources_1/bd/top/top.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_wrapper -part xc7z010clg400-1 -flatten_hierarchy none


write_checkpoint -force -noxdef top_wrapper.dcp

catch { report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb }
